package cloud.cholewa.message;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum MessageType {

    REQUEST_FOR_LOGIN("LOGIN_REQUEST"),
    RESPONSE_FOR_LOGIN("LOGIN_RESPONSE"),
    SERVER_OK("SERVER_OK"),

    REQUEST_END_SESSION("END"),

    CLIENT_CHAT("CLIENT_CHAT"),
    SERVER_CHAT("SERVER_CHAT"),

    REQUEST_CHANNEL_CHANGE("REQUEST_CHANNEL_CHANGE"),
    RESPONSE_CHANNEL_CHANGE_ERROR("RESPONSE_CHANNEL_CHANGE_ERROR"),
    RESPONSE_CHANNEL_CHANGE("RESPONSE_CHANNEL_CHANGE"),

    HISTORY_REQUEST("HISTORY_REQUEST"),
    HISTORY_BEGIN("HISTORY_BEGIN"),
    HISTORY_POSITION("HISTORY_POSITION"),
    HISTORY_END("HISTORY_END"),



    SERVER_COMMAND_FILE_TRANSFER("TRANSFER");

    private final String name;
}
