package cloud.cholewa.message;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum MessageType {

    REQUEST_FOR_LOGIN("LOGIN_REQUEST"),
    RESPONSE_FOR_LOGIN("LOGIN_RESPONSE"),
    SERVER_OK("SERVER_OK"),

    REQUEST_END_SESSION("END"),

    CLIENT_CHAT("CLIENT_CHAT"),
    SERVER_CHAT("SERVER_CHAT"),

    REQUEST_CHANNEL_CHANGE("REQUEST_CHANNEL_CHANGE"),
    RESPONSE_CHANNEL_CHANGE_ERROR("RESPONSE_CHANNEL_CHANGE_ERROR"),
    RESPONSE_CHANNEL_CHANGE("RESPONSE_CHANNEL_CHANGE"),

    HISTORY_REQUEST("HISTORY_REQUEST"),
    HISTORY_BEGIN("HISTORY_BEGIN"),
    HISTORY_POSITION("HISTORY_POSITION"),
    HISTORY_END("HISTORY_END"),

    FILE_SENDING_NOTIFY("FILE_SENDING_NOTIFY"),
    FILE_RECEIVING_READY("FILE_RECEIVING_READY"),
    FILE_TRANSFER_ERROR("FILE_TRANSFER_ERROR"),
    FILE_TRANSFER_REQUEST("FILE_TRANSFER_REQUEST"),
    FILE_RECEIVE_REQUEST("FILE_RECEIVE_REQUEST"),
    FILE_RECEIVING_FROM_SERVER_READY("FILE_RECEIVING_FROM_SERVER_READY"),


    SERVER_COMMAND_FILE_TRANSFER("TRANSFER");

    private final String name;
}
